### ISSUE TITLE
「ブラックジャックの戦略の歴史」の語句の修正

### ISSUE THREAD

**Issue by b1016207** [BeatTheDealerProject/MiddleReport2018#45]
・「ブラックジャックの戦略の歴史」の「パソコン」という言葉を正式名称に
・「ブラックジャックの戦略の歴史」の「カジノ側に禁止」「カジノから追放される」は正確ではないので共に「対策される」というように

**Comment by zakitaku** [comment]
※追加
・対策されているのはカウンティングのみ
